# Generated by Django 2.1.15 on 2022-03-20 20:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_auto_20220221_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('periodo', models.CharField(blank=True, choices=[('', 'Escolha um periodo'), ('manha', 'Manhã'), ('tarde', 'Tarde'), ('integral', 'Integral')], max_length=50, null=True, verbose_name='período da aula')),
                ('entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='entrada')),
                ('saida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='saida')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Pet')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('qtd_semana', models.CharField(blank=True, choices=[('', 'Escolha quantas vezes por semmana'), ('1', '1x por semana'), ('2', '2x por semana'), ('3', '3x por semana'), ('4', '4x por semana'), ('5', '5x por semana')], max_length=50, null=True, verbose_name='Vezes por semana')),
                ('periodo', models.CharField(blank=True, choices=[('', 'Escolha quantas vezes por semmana'), ('1', '1x por semana'), ('2', '2x por semana'), ('3', '3x por semana'), ('4', '4x por semana'), ('5', '5x por semana')], max_length=50, null=True, verbose_name='Vezes por semana')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Pet')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planos.Plano'),
        ),
    ]
