# Generated by Django 2.1.15 on 2022-03-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='avaliacao',
            field=models.BooleanField(default=False, verbose_name='avaliação'),
        ),
    ]
