# Generated by Django 2.1.15 on 2022-03-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0002_aula_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='mes_referencia',
            field=models.CharField(blank=True, choices=[('', 'Escolha um periodo'), ('janeiro', 'Janeiro'), ('fevereiro', 'fevereiro'), ('março', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Setembro'), ('outubro', 'Outubro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro')], max_length=50, null=True, verbose_name='Mês referência'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='periodo',
            field=models.CharField(blank=True, choices=[('', 'Escolha um periodo'), ('meio', 'meio período'), ('integral', 'período integral')], max_length=50, null=True, verbose_name='Período'),
        ),
    ]
