# Generated by Django 2.1.15 on 2022-04-06 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0003_auto_20220324_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='mes_referencia',
        ),
        migrations.AddField(
            model_name='plano',
            name='inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='início'),
        ),
    ]
