# Generated by Django 2.1.15 on 2022-04-14 19:50

import datetime
from django.db import migrations, models

from apps.planos.models import Aula


def datetime_to_date(apps, schema_editor):
    Aula = apps.get_model("planos", "Aula")
    for aula in Aula.objects.all():
        if aula.entrada:
            aula.data_aula = aula.entrada.date()
            aula.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0004_auto_20220406_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='data_aula',
            field=models.DateField(default=datetime.date.today, verbose_name='data da aula'),
        ),
        migrations.RunPython(datetime_to_date),
        migrations.RemoveField(
            model_name='aula',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='saida',
        ),
    ]
