# Generated by Django 3.1.2 on 2020-10-20 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('tipo_servico', models.CharField(choices=[('banho', 'Banho'), ('tosa', 'Tosa'), ('banho+tosa', 'Banho e tosa'), ('outros', 'Outros')], default='p', max_length=50, verbose_name='tipo de serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pagamento', models.CharField(choices=[('aguardando', 'Aguardando'), ('dinheiro', 'Dinheiro'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('transferencia', 'Transferência'), ('outros', 'Outros')], default='dinheiro', max_length=50, verbose_name='tipo de pagamento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('pets', models.ManyToManyField(blank=True, null=True, to='clientes.Pet')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
