# Generated by Django 3.1.2 on 2020-10-20 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_servico_data_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data_servico',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 6, 8, 59, 887951, tzinfo=utc), verbose_name='data do serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='pagamento',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('dinheiro', 'Dinheiro'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('transferencia', 'Transferência'), ('outros', 'Outros')], default='aguardando', max_length=50, verbose_name='tipo de pagamento'),
        ),
    ]
