# Generated by Django 3.2.7 on 2021-09-30 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20201020_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data_servico',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 19, 7, 13, 654445, tzinfo=utc), verbose_name='data do serviço'),
        ),
    ]
