# Generated by Django 2.1.15 on 2022-02-21 23:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_servico_data_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data_servico',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 23, 17, 16, 975325, tzinfo=utc), verbose_name='data do serviço'),
        ),
    ]
