# Generated by Django 2.1.15 on 2022-03-16 21:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20220221_2139'),
        ('financeiro', '0005_auto_20220221_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('item', models.CharField(max_length=150, verbose_name='item')),
                ('quantidate', models.IntegerField(default=0, verbose_name='quantidade')),
                ('valor_sugerido', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor sugerido')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Itens em Estoque',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('servico', models.CharField(blank=True, choices=[('', 'Escolha um serviço'), ('avaliacao', 'Avaliação'), ('meioperiodo', 'Daycare meio periodo'), ('integral', 'Daycare periodo integral'), ('banho', 'Banho'), ('tosa', 'Tosa'), ('banho+tosa', 'Banho e tosa'), ('outros', 'Outros')], max_length=50, null=True, verbose_name='tipo de serviço')),
                ('plano', models.CharField(blank=True, choices=[('', 'Escolha um plano'), ('meio1x', 'Daycare meio periodo 1x por semana'), ('meio2x', 'Daycare meio periodo 2x por semana'), ('meio3x', 'Daycare meio periodo 3x por semana'), ('meio4x', 'Daycare meio periodo 4x por semana'), ('meio5x', 'Daycare meio periodo 5x por semana'), ('integral1x', 'Daycare integral 1x por semana'), ('integral2x', 'Daycare integral 2x por semana'), ('integral3x', 'Daycare integral 3x por semana'), ('integral4x', 'Daycare integral 4x por semana'), ('integral5x', 'Daycare integral 5x por semana')], max_length=50, null=True, verbose_name='plano')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('data_servico', models.DateTimeField(default=datetime.datetime(2022, 3, 16, 21, 50, 30, 382496, tzinfo=utc), verbose_name='data do serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pagamento', models.CharField(choices=[('aguardando', 'Aguardando'), ('dinheiro', 'Dinheiro'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('transferencia', 'Transferência'), ('outros', 'Outros')], default='aguardando', max_length=50, verbose_name='tipo de pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('item_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.Estoque')),
                ('pets', models.ManyToManyField(blank=True, null=True, to='clientes.Pet')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='pets',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
