# Generated by Django 2.1.15 on 2022-03-16 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_auto_20220316_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(max_length=150, verbose_name='item')),
            ],
            options={
                'verbose_name': 'Categoria da Despesa',
                'verbose_name_plural': 'Categorias da Despesa',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('titulo', models.CharField(max_length=250, verbose_name='título')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('data_despesa', models.DateTimeField(default=datetime.datetime(2022, 3, 16, 22, 23, 47, 271578, tzinfo=utc), verbose_name='data do pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pagamento', models.CharField(choices=[('avista', 'À vista'), ('parcelado', 'Parcelado')], default='aguardando', max_length=50, verbose_name='tipo de pagamento')),
                ('parcelas', models.IntegerField(default=1)),
                ('categorias', models.ManyToManyField(blank=True, null=True, to='financeiro.Categoria')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(max_length=250)),
                ('cpf', models.CharField(default='000.000.000-00', max_length=14, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=250, verbose_name='endereço')),
                ('bairro', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=50, verbose_name='telefone')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('cargo', models.CharField(max_length=250)),
                ('arquivos', models.URLField(blank=True, help_text='Endereço para pasta de arquivos', null=True, verbose_name='arquivos')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_servico',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 22, 23, 47, 269965, tzinfo=utc), verbose_name='data do serviço'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.Funcionario'),
        ),
    ]
