# Generated by Django 2.1.15 on 2022-03-16 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_auto_20220316_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='qtd_item',
            field=models.IntegerField(default=0, help_text='Referente aos itens em estoque que foram vendidos', verbose_name='Quantidade de itens'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='financeiro.Categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_despesa',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 23, 31, 50, 822012, tzinfo=utc), verbose_name='data do pagamento'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_servico',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 23, 31, 50, 820600, tzinfo=utc), verbose_name='data do serviço'),
        ),
    ]
