# Generated by Django 2.1.15 on 2022-03-16 23:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_auto_20220316_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='quantidate',
            new_name='quantidade',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_despesa',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 23, 43, 43, 927200, tzinfo=utc), verbose_name='data do pagamento'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_servico',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 23, 43, 43, 925690, tzinfo=utc), verbose_name='data do serviço'),
        ),
    ]
