# Generated by Django 2.1.15 on 2022-03-20 20:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
        ('financeiro', '0009_auto_20220316_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planos.Aula'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_despesa',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data do pagamento'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_servico',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data do serviço'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='pets',
            field=models.ManyToManyField(to='clientes.Pet'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planos.Plano'),
        ),
    ]
