# Generated by Django 2.1.15 on 2022-04-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_auto_20220320_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='receita',
            name='pets',
            field=models.ManyToManyField(blank=True, null=True, to='clientes.Pet'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
