# Generated by Django 2.1.15 on 2022-02-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='arquivos',
            field=models.URLField(blank=True, help_text='Endereço para pasta de arquivos', null=True, verbose_name='arquivos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='pet',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='pet',
            name='peso',
            field=models.FloatField(default='0.0', help_text='Peso em Kg'),
        ),
    ]
